---
- name: "Get user GID"
  getent:
    database: passwd
    key: "{{ wg_system_user }}"

- name: Generate compose config
  template:
    src: "exporter-compose.yml"
    dest: "/etc/wireguard/exporter-compose.yml"
    owner: "{{ wg_system_user }}"
    group: "{{ wg_system_group }}"
    mode: "0400"

- name: Check if docker package is installed
  package:
    name: "docker"
    state: present
  check_mode: true
  changed_when: false
  register: _docker_package_check

- name: Ensure exporter is up
  shell: "docker compose -f /etc/wireguard/exporter-compose.yml up -d --force-recreate"
  args:
    executable: /bin/bash
  changed_when: false
  when: _docker_package_check is succeeded
