---
- name: Register passwd file
  getent:
    database: passwd
    key: "{{ wg_system_user }}"

- name: Generate compose config
  template:
    src: "docker-compose.yml"
    dest: "/etc/wireguard/{{ wg_interface }}-files/docker-compose.yml"
    owner: "{{ wg_system_user }}"
    group: "{{ wg_system_group }}"
    mode: "0400"

- name: Check if docker package is installed
  package:
    name: "docker"
    state: absent
  check_mode: true
  changed_when: false
  register: _docker_package_check
  until: _docker_package_check is succeeded
  delay: 5
  retries: 5

- name: Check docker service status
  systemd:
    name: "docker"
  register: _docker_service

- name: Ensure exporter is up
  shell: "docker compose -f /etc/wireguard/{{ wg_interface }}-files/docker-compose.yml up -d --force-recreate"
  args:
    executable: /bin/bash
  changed_when: false
  when: _docker_service.status.ActiveState == "active"
