---
# - name: Enable IPv4 traffic forwarding
#   sysctl:
#     name: net.ipv4.ip_forward
#     value: 1
#     sysctl_set: yes
#     state: present
#     reload: yes

# - name: Enable IPv4 forwarding continued
#   command: echo 1 > /proc/sys/net/ipv4/ip_forward

- name: Enable iptables service
  block:
    - name: Enable iptables service
      systemd:
        name: iptables
        state: started
        enabled: true
  rescue:
    - name: Enable iptables via "netfilter-persistent" service
      systemd:
        name: netfilter-persistent
        state: started
        enabled: true

- name: Allow input to wg interface from external
  iptables:
    chain: INPUT
    state: present
    destination_port: "{{ wg_port }}"
    ctstate: NEW,ESTABLISHED
    protocol: udp
    jump: ACCEPT
    state: present
    comment: "wg from external"
  notify: save_iptables_rules

- name: Allow forwarding (1/2)
  iptables:
    chain: FORWARD
    in_interface: "{{ ansible_default_ipv4.interface }}"
    out_interface: "{{ wg_interface }}"
    ctstate: NEW
    jump: ACCEPT
    state: present
    comment: "wg forward"

- name: Allow forwarding (2/2)
  iptables:
    chain: FORWARD
    in_interface: "{{ wg_interface }}"
    out_interface: "{{ ansible_default_ipv4.interface }}"
    ctstate: NEW
    jump: ACCEPT
    state: present
    comment: "wg forward"

- name: Allow NAT
  iptables:
    chain: POSTROUTING
    table: nat
    source: "{{ wg_ip_pool_part }}.0/24"
    jump: MASQUERADE
    state: present
    comment: "wg nat"
  notify: save_iptables_rules

- name: Allow client-to-client communication
  block:
    - name: Remove client-to-client isolation rule
      iptables:
        chain: FORWARD
        in_interface: wg0
        out_interface: wg0
        ctstate: NEW
        jump: REJECT
        reject_with: "icmp-net-prohibited"
        state: absent
        comment: "wg clients isolation"

    - name: Add client-to-client communication rule
      iptables:
        chain: FORWARD
        in_interface: wg0
        out_interface: wg0
        ctstate: NEW,ESTABLISHED
        jump: ACCEPT
        state: present
        comment: "wg client-to-client communication"
  when: not wg_isolate_clients
  notify: save_iptables_rules

- name: Isolate client-to-client communication
  block:
    - name: Remove client-to-client communication rule
      iptables:
        chain: FORWARD
        in_interface: wg0
        out_interface: wg0
        ctstate: NEW,ESTABLISHED
        jump: ACCEPT
        state: absent
        comment: "wg client-to-client communication"

    - name: Add client-to-client isolation rule
      iptables:
        chain: FORWARD
        in_interface: wg0
        out_interface: wg0
        ctstate: NEW
        jump: REJECT
        reject_with: "icmp-net-prohibited"
        state: present
        comment: "wg clients isolation"
  when: wg_isolate_clients | bool
  notify: save_iptables_rules
