---
- name: Enable iptables service
  systemd:
    name: iptables
    state: started
    enabled: true
  when: ansible_os_family == "RedHat"

- name: Enable netfilter-persistent (iptables) service
  systemd:
    name: netfilter-persistent
    state: started
    enabled: true
  when: ansible_os_family == "Debian"

- name: Allow input to wg interface from external
  iptables:
    chain: INPUT
    destination_port: "{{ wg_port }}"
    ctstate: NEW,ESTABLISHED
    protocol: udp
    jump: ACCEPT
    state: present
    comment: "wg from external"
  notify:
    - save_iptables_rules_redhat_ipv4
    - save_iptables_rules_debian_ipv4
    - save_iptables_rules_redhat_ipv6
    - save_iptables_rules_debian_ipv6

- name: Allow forwarding (1/2)
  iptables:
    chain: FORWARD
    in_interface: "{{ item }}"
    out_interface: "{{ wg_interface }}"
    jump: ACCEPT
    state: present
    comment: "wg forward from {{ item }} to {{ wg_interface }}"
  with_items: "{{ ansible_interfaces | reject('search', 'lo') | reject('search', '{{ wg_interface }}') }}"
  notify:
    - save_iptables_rules_redhat_ipv4
    - save_iptables_rules_debian_ipv4
    - save_iptables_rules_redhat_ipv6
    - save_iptables_rules_debian_ipv6

- name: Allow forwarding (2/2)
  iptables:
    chain: FORWARD
    in_interface: "{{ wg_interface }}"
    out_interface: "{{ item }}"
    jump: ACCEPT
    state: present
    comment: "wg forward from {{ wg_interface }} to {{ item }}"
  with_items: "{{ ansible_interfaces | reject('search', 'lo') | reject('search', '{{ wg_interface }}') }}"
  notify:
    - save_iptables_rules_redhat_ipv4
    - save_iptables_rules_debian_ipv4
    - save_iptables_rules_redhat_ipv6
    - save_iptables_rules_debian_ipv6

- name: Allow dns tcp access from wg
  iptables:
    chain: INPUT
    in_interface: "{{ wg_interface }}"
    source: "{{ wg_ipv4_pool }}"
    destination_port: "53"
    protocol: tcp
    jump: ACCEPT
    state: present
    comment: "dns tcp access from {{ wg_interface }}"
  notify:
    - save_iptables_rules_redhat_ipv4
    - save_iptables_rules_debian_ipv4
    - save_iptables_rules_redhat_ipv6
    - save_iptables_rules_debian_ipv6

- name: Allow dns udp access from wg
  iptables:
    chain: INPUT
    in_interface: "{{ wg_interface }}"
    source: "{{ wg_ipv4_pool }}"
    destination_port: "53"
    protocol: udp
    jump: ACCEPT
    state: present
    comment: "dns udp access from {{ wg_interface }}"
  notify:
    - save_iptables_rules_redhat_ipv4
    - save_iptables_rules_debian_ipv4
    - save_iptables_rules_redhat_ipv6
    - save_iptables_rules_debian_ipv6

- name: Allow NAT
  iptables:
    chain: POSTROUTING
    table: nat
    source: "{{ wg_ipv4_pool }}"
    jump: MASQUERADE
    state: present
    comment: "wg nat"
  notify:
    - save_iptables_rules_redhat_ipv4
    - save_iptables_rules_debian_ipv4
    - save_iptables_rules_redhat_ipv6
    - save_iptables_rules_debian_ipv6

- name: Allow client-to-client communication
  block:
    - name: Remove client-to-client isolation rule
      iptables:
        chain: FORWARD
        in_interface: "{{ wg_interface }}"
        out_interface: "{{ wg_interface }}"
        ctstate: NEW
        jump: REJECT
        reject_with: "icmp-net-prohibited"
        state: absent
        comment: "wg clients isolation"

    - name: Add client-to-client communication rule
      iptables:
        chain: FORWARD
        in_interface: "{{ wg_interface }}"
        out_interface: "{{ wg_interface }}"
        ctstate: NEW,ESTABLISHED
        jump: ACCEPT
        state: present
        comment: "wg client-to-client communication"
  when: not wg_isolate_clients
  notify:
    - save_iptables_rules_redhat_ipv4
    - save_iptables_rules_debian_ipv4
    - save_iptables_rules_redhat_ipv6
    - save_iptables_rules_debian_ipv6

- name: Isolate client-to-client communication
  block:
    - name: Remove client-to-client communication rule
      iptables:
        chain: FORWARD
        in_interface: "{{ wg_interface }}"
        out_interface: "{{ wg_interface }}"
        ctstate: NEW,ESTABLISHED
        jump: ACCEPT
        state: absent
        comment: "wg client-to-client communication"

    - name: Add client-to-client isolation rule
      iptables:
        chain: FORWARD
        in_interface: "{{ wg_interface }}"
        out_interface: "{{ wg_interface }}"
        ctstate: NEW
        jump: REJECT
        reject_with: "icmp-net-prohibited"
        state: present
        comment: "wg clients isolation"
  when: wg_isolate_clients | bool
  notify:
    - save_iptables_rules_redhat_ipv4
    - save_iptables_rules_debian_ipv4
    - save_iptables_rules_redhat_ipv6
    - save_iptables_rules_debian_ipv6
