---
# - name: Enable IPv4 traffic forwarding
#   sysctl:
#     name: net.ipv4.ip_forward
#     value: 1
#     sysctl_set: yes
#     state: present
#     reload: yes

# - name: Enable IPv4 forwarding continued
#   command: echo 1 > /proc/sys/net/ipv4/ip_forward

- name: Enable iptables service
  block:
    - name: Enable iptables service
      systemd:
        name: iptables
        state: started
        enabled: true
  rescue:
    - name: Enable iptables via "netfilter-persistent" service
      systemd:
        name: netfilter-persistent
        state: started
        enabled: true

- name: Allow client-to-client communication
  block:
    - name: Remove client-to-client isolation rule
      iptables:
        chain: FORWARD
        in_interface: wg0
        out_interface: wg0
        ctstate: NEW
        jump: REJECT
        reject_with: "icmp-net-prohibited"
        state: absent
        comment: "wg clients isolation"

    - name: Add client-to-client communication rule
      iptables:
        chain: FORWARD
        in_interface: wg0
        out_interface: wg0
        ctstate: NEW,ESTABLISHED
        jump: ACCEPT
        state: present
        comment: "wg client-to-client communication"
  when: not wg_isolate_clients
  notify: save_rules

- name: Isolate client-to-client communication
  block:
    - name: Remove client-to-client communication rule
      iptables:
        chain: FORWARD
        in_interface: wg0
        out_interface: wg0
        ctstate: NEW,ESTABLISHED
        jump: ACCEPT
        state: absent
        comment: "wg client-to-client communication"

    - name: Add client-to-client isolation rule
      iptables:
        chain: FORWARD
        in_interface: wg0
        out_interface: wg0
        ctstate: NEW
        jump: REJECT
        reject_with: "icmp-net-prohibited"
        state: present
        comment: "wg clients isolation"
  when: wg_isolate_clients | bool
  notify: save_rules
