---
- name: Ensure directories exist
  file:
    path: "{{ item }}"
    recurse: true
    owner: "root"
    group: "root"
    state: directory
    mode: "0755"
  with_items:
    [
      "/etc/wireguard/client-config",
      "/etc/wireguard/keys",
      "/etc/wireguard/psk",
      "/etc/wireguard/pub",
    ]

- name: Generate server private key
  shell: "wg genkey > /etc/wireguard/keys/{{ inventory_hostname }}-server.key"
  args:
    executable: /bin/bash
  changed_when: false

- name: Generate server public key
  shell: "set -eo pipefail &&
    wg genkey | tee /etc/wireguard/keys/{{ inventory_hostname }}-server.key |
    wg pubkey > /etc/wireguard/pub/{{ inventory_hostname }}-server-pub.key"
  args:
    executable: /bin/bash
  changed_when: false

# - name: Generate PSK for client
#   shell: "wg genpsk > /etc/wireguard/psk/{{ inventory_hostname }}-client{{ wg_octet_count }}.psk"
#   args:
#     executable: /bin/bash
#   changed_when: false

# - name: Generate private key for client
#   shell: "wg genkey > /etc/wireguard/keys/{{ inventory_hostname }}-client{{ wg_octet_count }}.key"
#   args:
#     executable: /bin/bash
#   changed_when: false

# - name: Generate public key for client
#   shell: "set -eo pipefail &&
#     wg genkey | tee /etc/wireguard/keys/{{ inventory_hostname }}-client{{ wg_octet_count }}.key |
#     wg pubkey > /etc/wireguard/pub/{{ inventory_hostname }}-client{{ wg_octet_count }}-pub.key"
#   args:
#     executable: /bin/bash
#   changed_when: false

- name: Register server private key
  shell: "cat /etc/wireguard/keys/{{ inventory_hostname }}-server.key"
  args:
    executable: /bin/bash
  changed_when: false
  register: "server_private_key"

- name: Register server public key
  shell: "cat /etc/wireguard/pub/{{ inventory_hostname }}-server-pub.key"
  args:
    executable: /bin/bash
  changed_when: false
  register: "server_public_key"

- name: Ensure permissions are secure
  file:
    path: "/etc/wireguard"
    state: directory
    recurse: true
    owner: "root"
    group: "root"
    mode: "0600"

- name: Add octet.count file
  lineinfile:
    path: "/etc/wireguard/octet.count"
    line: "%{{ wg_octet_count }}"
    state: present
    owner: "root"
    group: "root"
    mode: "0600"
    create: true

- name: Generate server config
  template:
    src: "server.conf.j2"
    dest: "/etc/wireguard/{{ wg_interface }}.conf"
    owner: "root"
    group: "root"
    mode: "0600"
  notify: restart_wireguard

- name: Generate interface config
  template:
    src: "interface.conf.j2"
    dest: "{{ wg_interface_path }}"
    owner: "root"
    group: "root"
    mode: "0644"
  notify: restart_wireguard

- name: Generate add-user script
  template:
    src: "add-user.sh.j2"
    dest: "/etc/wireguard/add-user.sh"
    owner: "root"
    group: "root"
    mode: "0700"

- name: Enable service
  systemd:
    name: "wg-quick@{{ wg_interface }}"
    enabled: true
