---
- include_tasks: "force_update.yml"
  when: wg_force_update | bool

- name: Check if server config file exists
  stat:
    path: "{{ wg_server_config_path }}"
  register: _wg_file_check

- include_tasks: "packages.yml"

- include_tasks: "firewall_ipv4.yml"

- include_tasks: "firewall_ipv6.yml"
  when: wg_ipv6_support | bool

- include_tasks: "preinstall.yml"

- include_tasks: "install.yml"
  when: not _wg_file_check.stat.exists

- include_tasks: "postinstall.yml"

- include_tasks: "exporter.yml"
  when: wg_deploy_exporter | bool
