---
- name: Ensure base directories absent
  file:
    path: "/etc/wireguard"
    state: absent
  when: wg_force_update | bool

- name: Check if server config already exists
  stat:
    path: "/etc/wireguard/{{ wg_interface }}.conf"
  register: _wg_file_check

- name: Stop service
  shell: "[[ -e {{ wg_interface_path }} ]] && wg-quick down {{ wg_interface }} || true"
  args:
    executable: /bin/bash
  when: _wg_file_check.stat.exists

- include_tasks: "packages.yml"

- include_tasks: "firewall.yml"

- include_tasks: "generate_keys.yml"
  when: not _wg_file_check.stat.exists
# - include_tasks: "download_configs.yml"
