---
- name: Ensure base directory is absent
  file:
    path: "/etc/wireguard"
    state: absent
  when: wg_force_update | bool

- name: Check if server config already exists
  stat:
    path: "/etc/wireguard/{{ wg_interface }}.conf"
  register: _wg_file_check

- include_tasks: "packages.yml"

- include_tasks: "firewall.yml"

- include_tasks: "preinstall.yml"

- include_tasks: "install.yml"
  when: not _wg_file_check.stat.exists

- include_tasks: "postinstall.yml"

- include_tasks: "exporter.yml"
  when: wg_deploy_exporter | bool
