---
- name: Ensure apt cache are updated
  apt:
    update_cache: true
    cache_valid_time: 3600
  register: _download_package
  until: _download_package is succeeded
  retries: 5
  when: ansible_os_family == "Debian"

- name: Ensure backports repository is set
  apt_repository:
    repo: "deb http://deb.debian.org/debian {{ ansible_distribution_release }}-backports main"
    state: present
    install_python_apt: true
    update_cache: true
  when:
    - ansible_distribution == "Debian"
    - ansible_distribution_major_version in ["10", "11"]

- name: Ensure backports source repository is set
  apt_repository:
    repo: "deb-src http://deb.debian.org/debian {{ ansible_distribution_release }}-backports main"
    state: present
    install_python_apt: true
    update_cache: true
  when:
    - ansible_distribution == "Debian"
    - ansible_distribution_major_version in ["10", "11"]

- name: Ensure iptables-services package is installed
  package:
    state: present
    name: iptables-services
  register: _download_package
  until: _download_package is succeeded
  retries: 5
  when: ansible_os_family == "RedHat"

- name: Ensure iptables-persistent package is installed
  package:
    state: present
    name: iptables-persistent
  register: _download_package
  until: _download_package is succeeded
  retries: 5
  when: ansible_os_family == "Debian"

- name: Ensure dependencies are installed
  package:
    state: present
    name:
      - qrencode
      - curl
  register: _download_package
  until: _download_package is succeeded
  retries: 5

- name: Ensure wireguard is installed
  package:
    state: present
    name: wireguard
  register: _download_package
  until: _download_package is succeeded
  retries: 5
