---
- name: Create system group
  group:
    name: "{{ wg_system_group }}"
    system: true
    state: present
  when: wg_system_group != "root"

- name: Create system user
  user:
    name: "{{ wg_system_user }}"
    system: true
    shell: "/usr/sbin/nologin"
    group: "{{ wg_system_group }}"
    create_home: false
  when: wg_system_user != "root"

- name: Enable traffic forwarding (ipv4)
  sysctl:
    name: net.ipv4.ip_forward
    value: 1
    sysctl_set: true
    state: present
    reload: true

- name: Enable traffic forwarding (ipv6)
  sysctl:
    name: net.ipv6.conf.all.forwarding
    value: 2
    sysctl_set: true
    state: present
    reload: true
  when: wg_ipv6_support | bool

- name: Make sure that ipv6 is enabled on device
  sysctl:
    name: "{{ item }}"
    value: 0
    sysctl_set: true
    state: present
    reload: true
  with_items:
    ["net.ipv6.conf.all.disable_ipv6", "net.ipv6.conf.default.disable_ipv6"]
  when: wg_ipv6_support | bool
