---
- name: restart_wireguard
  systemd:
    name: "wg-quick@{{ wg_interface }}"
    state: restarted

- name: stop_wireguard
  systemd:
    name: "wg-quick@{{ wg_interface }}"
    state: stopped

- name: save_iptables_rules
  community.general.iptables_state:
    ip_version: "ipv4"
    state: saved
    path: "/etc/sysconfig/iptables"
  when: ansible_os_family == "RedHat"
  listen: save_iptables_rules

- name: save_iptables_rules
  community.general.iptables_state:
    ip_version: "ipv4"
    state: saved
    path: "/etc/iptables/rules.v4"
  when: ansible_os_family == "Debian"
  listen: save_iptables_rules
