---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: virtualbox
lint: |
  ansible-lint .
platforms:
  - name: host1
    box: debian/bullseye64
    memory: 4096
    cpus: 4
    interfaces:
      - network_name: private_network
        ip: 192.168.56.10
    provider_raw_config_args:
      - "customize [ 'modifyvm', :id, '--natdnshostresolver1', 'on' ]"
    config_options:
      ssh.keep_alive: yes
      ssh.remote_user: "'vagrant'"
provisioner:
  name: ansible
  config_options:
    defaults:
      display_skipped_hosts: false
  lint:
    name: ansible-lint
scenario:
  test_sequence:
    - dependency
    - lint
    - cleanup
    - destroy
    - syntax
    - create
    - converge
    - verify
    - converge
    - verify
    - destroy
verifier:
  name: ansible
